/*
 * MenuMaintenance.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.seiryo.edu.entity.Menu;
import com.seiryo.edu.service.MenuService;
import com.seiryo.edu.util.DBUtil;

/**
 *
 * @author  __USER__
 */
public class AdminMenuEdit extends javax.swing.JFrame {

	/** Creates new form MenuMaintenance */
	public AdminMenuEdit() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jLabel1.setText("\u5957\u9910\u540d\u79f0\uff1a");

		jLabel2.setText("\u5957\u9910\u4ef7\u683c\u533a\u95f4\uff1a");

		jLabel3.setText("\u2014\u2014");

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setShowHorizontalLines(false);
		jTable1.setShowVerticalLines(false);
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel4.setText("\u8868\u5355\u64cd\u4f5c");

		jLabel5.setText("\u5957\u9910\u540d\u79f0\uff1a");

		jLabel6.setText("\u5957\u9910\u63cf\u8ff0");

		jLabel7.setText("\u5957\u9910\u4ef7\u683c\uff1a ");

		jLabel8.setText("\u7f16\u53f7\uff1a");

		jLabel9.setText("\u5957\u9910\u56fe\u7247\uff1a");

		jButton2.setText("\u4fee\u6539");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField6.setEnabled(false);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(55, 55, 55)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		858,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jButton2)
																.addGap(44, 44,
																		44)
																.addComponent(
																		jButton3)
																.addGap(25, 25,
																		25))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabel4)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(9,
																						9,
																						9)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel6)
																												.addGap(18,
																														18,
																														18)
																												.addComponent(
																														jScrollPane2,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														414,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel5)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														jTextField4,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														109,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGap(69,
																														69,
																														69)
																												.addComponent(
																														jLabel7)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														jTextField5,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														112,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGap(59,
																														59,
																														59)
																												.addComponent(
																														jLabel8)
																												.addGap(18,
																														18,
																														18)
																												.addComponent(
																														jTextField6,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														116,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGap(58,
																														58,
																														58)
																												.addComponent(
																														jLabel9)
																												.addGap(18,
																														18,
																														18)
																												.addComponent(
																														jTextField7,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														108,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGap(91,
																						91,
																						91))
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		1053,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel1)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						134,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						354,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel2)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						73,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jLabel3)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						74,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(55,
																						55,
																						55)
																				.addComponent(
																						jButton1)
																				.addGap(64,
																						64,
																						64))))
								.addGap(73, 73, 73)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1))
								.addGap(29, 29, 29)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29)
								.addComponent(jLabel4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										36,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(219,
																		219,
																		219)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton2)
																				.addComponent(
																						jButton3)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(37, 37,
																		37)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						jTextField5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel9)
																				.addComponent(
																						jTextField6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jTextField7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jTextField4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(38, 38,
																		38)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel6))))
								.addGap(24, 24, 24)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	/*
	 * 模糊查询
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String name = this.jTextField1.getText();
		String minPrice = this.jTextField2.getText();
		String maxPrice = this.jTextField3.getText();
		int minPrice1 = 0,maxPrice1 = 0;
		if(!"".equals(minPrice)){
			minPrice1 = Integer.parseInt(minPrice);
		}
		if(!"".equals(maxPrice)){
			maxPrice1 = Integer.parseInt(maxPrice);
		}
		List<Menu> list = service.furryQueryMenu(name, minPrice1, maxPrice1);
		if (list == null) {
			this.dtm = new DefaultTableModel(null, vHead1);
			this.jTable1.setModel(dtm);
			return;
		}
		vData1.clear();
		for (Menu i : list) {
			Vector vMenu = new Vector();
			vMenu.add(i.getMenu_id());
			vMenu.add(i.getName());
			vMenu.add(i.getDescribe());
			vMenu.add(i.getUnit_price());
			vData1.add(vMenu);
		}
		this.dtm = new DefaultTableModel(vData1, vHead1);
		this.jTable1.setModel(dtm);
	}
	/*
	 * 通过table1得到菜单
	 */
	private Menu getText(){
		int row = this.jTable1.getSelectedRow();
		if(row ==-1){
			jPane.showMessageDialog(this, "请选择菜单");
			return null;
		}else{
			dtm = (DefaultTableModel) jTable1.getModel();
			String id = String.valueOf(dtm.getValueAt(row, 0));
			String name = String.valueOf(dtm.getValueAt(row, 1));
			String describe = String.valueOf(dtm.getValueAt(row, 2));
			String price = String.valueOf(dtm.getValueAt(row, 3));
			Menu menu = new Menu(Integer.parseInt(id),name,describe,Integer.parseInt(price));
			return menu;
		}
	}
	/*
	 * 点击table1
	 */
	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		Menu menu = getText();
		if(menu == null){
			return;
		}
		this.jTextField6.setText(String.valueOf(menu.getMenu_id()));
		this.jTextField4.setText(menu.getName());
		this.jTextField5.setText(String.valueOf(menu.getUnit_price()));
		this.jTextArea1.setText(String.valueOf(menu.getDescribe()));
	}
	/*
	 * 删除
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Menu menu = getText();
		if(menu == null){
			return;
		}
		service.setDeleteId(menu.getMenu_id());
		DeleteComfirm delete = new DeleteComfirm(this);
		delete.show();
		
	}
	/*
	 * 选定菜单修改功能
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		Menu menu = getText();
		if(menu == null){
			return;
		}
		String price = this.jTextField5.getText();
		int id = menu.getMenu_id();
		String name = this.jTextField4.getText();
		String describe = this.jTextArea1.getText();
		boolean bo = service.editMenu(id,name,describe, price);
		if(bo){
			jPane.showMessageDialog(this, "修改成功！");
			updateTable();
			this.jTextField5.setText("");
			this.jTextField6.setText("");
			this.jTextField4.setText("");
			this.jTextArea1.setText("");
		}
	}
	/*
	 * 为了外部调用刷新表格
	 */
	public void refreshTable() {
	    updateTable();
	}
	/*
	 * 刷新表格
	 */
	private void updateTable(){
		List<Menu> menu = service.queryAll();
		this.vHead1 = new Vector();
		this.vData1 = new Vector();
		vHead1.add("序号");
		vHead1.add("套餐名称");
		vHead1.add("套餐描述");
		vHead1.add("套餐价格");
		for (Menu i : menu) {
			Vector vMenu = new Vector();
			vMenu.add(i.getMenu_id());
			vMenu.add(i.getName());
			vMenu.add(i.getDescribe());
			vMenu.add(i.getUnit_price());
			vData1.add(vMenu);
		}
		this.dtm = new DefaultTableModel(vData1, vHead1);
		this.jTable1.setModel(dtm);
	}
	/*
	 * 开始界面
	 */
	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		updateTable();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminMenuEdit().setVisible(true);
			}
		});
	}
	
	Vector vHead1 = null;
	Vector vData1 = null;
	DefaultTableModel dtm = null;
	MenuService service = new MenuService();
	JOptionPane jPane = new JOptionPane();
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	// End of variables declaration//GEN-END:variables

}