/*
 * AdminOrderExecute.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.seiryo.edu.entity.Menu;
import com.seiryo.edu.entity.Order;
import com.seiryo.edu.entity.OrdersDetail;
import com.seiryo.edu.entity.Users;
import com.seiryo.edu.service.OrderDetailService;
import com.seiryo.edu.service.OrderService;
import com.seiryo.edu.service.UserService;

/**
 *
 * @author  __USER__
 */
public class AdminOrderProcessing extends javax.swing.JFrame {

	/** Creates new form AdminOrderExecute */
	public AdminOrderProcessing() {
		initComponents();
	}
	//你先演示一下问题
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jLabel1.setText("\u8ba2\u5355\u53f7\uff1a");

		jButton1.setText("\u8ba2\u5355\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setShowHorizontalLines(false);
		jTable1.setShowVerticalLines(false);
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable2.setShowHorizontalLines(false);
		jTable2.setShowVerticalLines(false);
		jScrollPane2.setViewportView(jTable2);

		jLabel2.setText("\u70b9\u9910\u4eba\uff1a");

		jTextField2.setEnabled(false);

		jLabel3.setText("\u8ba2\u5355\u72b6\u6001\uff1a");

		jTextField3.setEnabled(false);

		jLabel4.setText("\u603b\u6570\u91cf\uff1a");

		jTextField4.setEditable(false);

		jLabel5.setText("\u603b\u91d1\u989d\uff1a");

		jTextField5.setEnabled(false);

		jButton2.setText("\u53d6\u6d88\u8ba2\u5355");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jRadioButton1.setText("\u786e\u8ba4\u8ba2\u5355");

		jRadioButton2.setText("\u53bb\u9001\u9910");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonGroup1.add(jRadioButton1);
				buttonGroup1.add(jRadioButton2);
				buttonGroup1.add(jRadioButton3);
				buttonGroup1.add(jRadioButton4);
			}
		});

		jRadioButton3.setText("\u5df2\u5b8c\u6210");

		jRadioButton4.setText("\u5220\u9664\u8ba2\u5355");

		jButton3.setText("\u63d0\u4ea4");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(120,
																						120,
																						120)
																				.addComponent(
																						jLabel1)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						127,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(34,
																						34,
																						34)
																				.addComponent(
																						jButton1)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						549,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel2)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						103,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addGap(36,
																						36,
																						36)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						111,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						559,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButton2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						144,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addGap(27,
																										27,
																										27)
																								.addComponent(
																										jTextField3,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										180,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(30,
																										30,
																										30)
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jTextField4,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										88,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(31,
																										31,
																										31)
																								.addComponent(
																										jLabel5)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jTextField5,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										86,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jRadioButton1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jRadioButton2))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jRadioButton3)
																								.addGap(22,
																										22,
																										22)
																								.addComponent(
																										jRadioButton4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jButton3)))))
								.addGap(39, 39, 39)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(33, 33,
																		33)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton1)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														268,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														233,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jButton2)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton1)
												.addComponent(jRadioButton2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton3)
												.addComponent(jButton3)
												.addComponent(jRadioButton4))
								.addContainerGap(35, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	/*
	 * 展示field的text
	 */
	private void showTextField(){
		int row = this.jTable1.getSelectedRow();
		dtm = (DefaultTableModel) jTable1.getModel();
		this.jTextField3.setText((String)dtm.getValueAt(row, 3));
		this.jTextField4.setText(String.valueOf(dtm.getValueAt(row, 1)));
		this.jTextField5.setText(String.valueOf(dtm.getValueAt(row, 2)));
		this.jTextField2.setText(String.valueOf(dtm.getValueAt(row, 4)));
	}
	/*
	 * 点击table1显示详细order
	 */
	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		int row = this.jTable1.getSelectedRow();
		if (row == -1) {
			jPane.showMessageDialog(this, "请选择菜品！");
			return;
		}
		dtm = (DefaultTableModel) jTable1.getModel();
		String orderId = (String) dtm.getValueAt(row, 0);
		List<OrdersDetail> list = dService.queryDetail(orderId);
		vData2.clear();
		for (OrdersDetail i : list) {
			Vector vDatail = new Vector();
			vDatail.add(i.getMenu_id());
			vDatail.add(i.getName());
			vDatail.add(i.getAmount());
			vDatail.add(i.getUnit_price());
			vDatail.add(i.getTotal_price());
			vData2.add(vDatail);
		}
		DefaultTableModel model2 = new DefaultTableModel(vData2, vHead2);
		jTable2.setModel(model2);
		showTextField();
	}
	/*
	 * 订单号的模糊查询
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		vData1.clear();
		String id = this.jTextField1.getText();
		if ("".equals(id)) {
			table1AllShow();
			return;
		}
		List<Order> list = oService.queryById(id);
		if (list.size() != 0) {
			vData1.clear();
			for (Order order : list) {
				Vector vOrder = new Vector();
				vOrder.add(order.getOrder_id());
				vOrder.add(order.getQuantity());
				vOrder.add(order.getTotal_price());
				vOrder.add(order.getOrder_status());
				vData1.add(vOrder);
				this.dtm = new DefaultTableModel(vData1, vHead1);
				this.jTable1.setModel(dtm);
			}
			return;
		}
		this.dtm = new DefaultTableModel(null, vHead1);
		this.jTable1.setModel(dtm);
	}

	/*
	 * 显示table1中所有的order信息
	 */
	private void table1AllShow() {
		List<Order> order = oService.queryOrder();
		this.vHead1 = new Vector();
		this.vData1 = new Vector();
		vHead1.add("订单编号");
		vHead1.add("订单商品数量");
		vHead1.add("订单总金额");
		vHead1.add("订单状态");
		vHead1.add("点餐人");
		for (Order i : order) {
			Vector vOrder = new Vector();
			vOrder.add(i.getOrder_id());
			vOrder.add(i.getQuantity());
			vOrder.add(i.getTotal_price());
			vOrder.add(i.getOrder_status());
			int userId = i.getUserId();
			String userName = userService.queryNameById(userId);
			vOrder.add(userName);
			vData1.add(vOrder);
		}
		this.dtm = new DefaultTableModel(vData1, vHead1);
		this.jTable1.setModel(dtm);
	}
	/*
	 * 开始界面
	 */
	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		table1AllShow();
		this.vHead2 = new Vector();
		this.vData2 = new Vector();
		vHead2.add("套餐编号");
		vHead2.add("套餐名称");
		vHead2.add("套餐数量");
		vHead2.add("套餐单价");
		vHead2.add("套餐金额");
		this.dtm = new DefaultTableModel(vData2, vHead2);
		this.jTable2.setModel(dtm);
	}
	/*
	 * 在未处理状态时取消订单
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		int row = this.jTable1.getSelectedRow();
		if (row == -1) {
			jPane.showMessageDialog(this, "请选择菜品！");
			return;
		}
		dtm = (DefaultTableModel) jTable1.getModel();
		String status = (String) dtm.getValueAt(row, 3);
		if(!"未处理".equals(status)){
			jPane.showMessageDialog(this, "订单已经处理，取消失败！");
			return;
		}
		String orderId = (String) dtm.getValueAt(row, 0);
		boolean hadDelete = oService.cancelStatus(orderId,"已取消");
		if (hadDelete) {
			jPane.showMessageDialog(this, "取消成功！");
			table1AllShow();
		}
	}
	/*
	 * 在未完成状态时改变订单状态
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		int row = this.jTable1.getSelectedRow();
		if (row == -1) {
			jPane.showMessageDialog(this, "请选择菜品！");
			return;
		}
		dtm = (DefaultTableModel) jTable1.getModel();
		String status = (String) dtm.getValueAt(row, 3);
		if ("已完成".equals(status)) {
			jPane.showMessageDialog(this, "订单已完成，操作失败！");
			return;
		}
		String orderId = (String) dtm.getValueAt(row, 0);
		boolean hadDelete = false;
		 if (this.jRadioButton1.isSelected()) {
			  hadDelete = oService.cancelStatus(orderId,"确认订单");
         } else if (this.jRadioButton2.isSelected()) {
        	  hadDelete = oService.cancelStatus(orderId,"去送餐");
         } else if (this.jRadioButton3.isSelected()) {
        	 hadDelete = oService.cancelStatus(orderId,"已完成");
         } else if (this.jRadioButton4.isSelected()) {
        	 dService.deleteByOrderId(orderId);
        	 oService.deleteOrder(orderId);
        	 hadDelete = true;
         }
		if (hadDelete) {
			jPane.showMessageDialog(this, "操作成功！");
			table1AllShow();
			this.jTextField3.setText("");
			this.jTextField4.setText("");
			this.jTextField5.setText("");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminOrderProcessing().setVisible(true);
			}
		});
	}
	UserService userService = new UserService();
	JOptionPane jPane = new JOptionPane();
	Vector vHead2 = null;
	Vector vData2 = null;
	DefaultTableModel dtm = null;
	Vector vHead1 = null;
	Vector vData1 = null;
	OrderService oService = new OrderService();
	OrderDetailService dService = new OrderDetailService();
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}