/*
 * AdminMenu.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

/**
 *
 * @author  __USER__
 */
public class AdminMenu extends javax.swing.JFrame {

	/** Creates new form AdminMenu */
	public AdminMenu() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("\u5957\u9910\u4fe1\u606f\u7ba1\u7406");

		jMenuItem1.setText("\u65b0\u589e\u5957\u9910");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("\u5957\u9910\u7ef4\u62a4");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u8ba2\u5355\u7ba1\u7406");

		jMenuItem3.setText("\u8ba2\u5355\u5904\u7406");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("\u5176\u4ed6");

		jMenuItem4.setText("\u9000\u51fa\u7cfb\u7edf");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem4);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1080,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 546,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	/*
	 * 退出界面
	 */
	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		exit.show();
	}
	/*
	 * 退出process界面
	 */
	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		process.show();
	}
	/*
	 * 菜单编辑界面
	 */
	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		edit.show();
	}
	/*
	 * 添加菜单界面
	 */
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		add.show();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminMenu().setVisible(true);
			}
		});
	}
	ExitComfirm exit = new ExitComfirm();
	AdminMenuAdd add = new AdminMenuAdd();
	AdminMenuEdit edit = new AdminMenuEdit();
	AdminOrderProcessing process = new AdminOrderProcessing();
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	// End of variables declaration//GEN-END:variables

}