/*
 * DeleteComfirm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import com.seiryo.edu.entity.Menu;
import com.seiryo.edu.service.MenuService;
import com.seiryo.edu.service.OrderDetailService;

/**
 *
 * @author  __USER__
 */
public class DeleteComfirm extends javax.swing.JFrame {

	/** Creates new form DeleteComfirm */
	public DeleteComfirm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u786e\u5b9a\u8981\u5220\u9664\u8fd9\u6761\u4fe1\u606f\u5417\uff1f");

		jButton1.setText("\u662f");
		jButton1.setActionCommand("jButton1");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u5426");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u53d6\u6d88");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(89, 89, 89)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		49,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)
																.addGap(39, 39,
																		39)
																.addComponent(
																		jButton3)
																.addGap(51, 51,
																		51)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(40, Short.MAX_VALUE)
								.addComponent(jLabel1)
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2)
												.addComponent(jButton3))
								.addGap(40, 40, 40)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}
	/*
	 * µã»÷ÊÇ
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		int id = mService.getDeleteId();
		boolean bo1 = oService.deleteByMenuId(id);
		boolean bo2 = mService.deleteMenu(id);
		adminMenuEdit.refreshTable();
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeleteComfirm().setVisible(true);
			}
		});
	}
	private AdminMenuEdit adminMenuEdit;

	public DeleteComfirm(AdminMenuEdit adminMenuEdit) {
	    this.adminMenuEdit = adminMenuEdit;
	    initComponents();
	}
	OrderDetailService oService = new OrderDetailService();
	MenuService mService = new MenuService();
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}