/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import javax.swing.JOptionPane;

import com.seiryo.edu.entity.Users;
import com.seiryo.edu.service.UserService;
import com.seiryo.edu.service.imp.UserServiceImp;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/** Creates new form Login */
	public Login() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u70b9\u9910\u7cfb\u7edf\u6b22\u8fce\u60a8");

		jLabel2.setText("\u7528\u6237\u540d");

		jLabel3.setText("\u5bc6\u7801");

		jButton3.setText("\u6ce8\u518c\u65b0\u7528\u6237");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(95, 95, 95)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel3))
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jPasswordField1,
																						javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						177,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel1)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addGap(55, 55,
																		55)
																.addComponent(
																		jButton2)
																.addGap(49, 49,
																		49)
																.addComponent(
																		jButton3)))
								.addContainerGap(39, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(36, 36, 36)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(47, 47, 47)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addGap(50, 50, 50)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1)
												.addComponent(jButton3))
								.addContainerGap(52, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	/*
	 * 重置
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextField1.setText("");
		this.jPasswordField1.setText("");
	}
	/*
	 * 显示注册界面
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		register.show();
	}
	/*
	 * 登入
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String name = this.jTextField1.getText();
		String pwd = this.jPasswordField1.getText();
		if (name.isEmpty() || pwd.isEmpty()) {
			jPane.showMessageDialog(this, "姓名和密码不能为空！");
			return;
		}
		int id = userService.queryUser(new Users(name, pwd));
		if (id != -1) {
			jPane.showMessageDialog(this, "登录成功！");
			menu.show();
		} else {
			jPane.showMessageDialog(this, "用户名或密码不存在");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	OrderMenu menu = new OrderMenu();
	Register register = new Register();
	JOptionPane jPane = new JOptionPane();
	UserServiceImp userService = new UserService();
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}