/*
 * OrderMenu.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

/**
 *
 * @author  __USER__
 */
public class OrderMenu extends javax.swing.JFrame {

	/** Creates new form OrderMenu */
	public OrderMenu() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("\u7528\u6237\u70b9\u5355");

		jMenuItem1.setText("\u5f00\u59cb\u70b9\u5355");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u8ba2\u5355\u8be6\u60c5");

		jMenuItem2.setText("\u67e5\u770b\u8ba2\u5355");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem2);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("\u5176\u4ed6");

		jMenuItem4.setText("\u4fe1\u606f\u4fee\u6539");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem4);

		jMenuItem3.setText("\u9000\u51fa\u7cfb\u7edf");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem3);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1032,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 444,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		exit.show();
	}

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		userInfo.show();
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		detail.show();
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		main.show();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new OrderMenu().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	ExitComfirm exit = new ExitComfirm();
	UserInfoEdit userInfo = new UserInfoEdit();
	OrderMain main = new OrderMain();
	OrderDetail detail = new OrderDetail();
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	// End of variables declaration//GEN-END:variables

}