/*
 * OrderDetail.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.seiryo.edu.entity.Menu;
import com.seiryo.edu.entity.Order;
import com.seiryo.edu.entity.OrdersDetail;
import com.seiryo.edu.entity.Users;
import com.seiryo.edu.service.OrderDetailService;
import com.seiryo.edu.service.OrderService;
import com.seiryo.edu.service.UserService;

/**
 *
 * @author  __USER__
 */
public class OrderDetail extends javax.swing.JFrame {

	/** Creates new form OrderDetail */
	public OrderDetail() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jTextField2 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jLabel1.setText("\u8ba2\u5355\u53f7\uff1a");

		jButton1.setText("\u8ba2\u5355\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setShowHorizontalLines(false);
		jTable1.setShowVerticalLines(false);
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable2.setShowHorizontalLines(false);
		jTable2.setShowVerticalLines(false);
		
		jScrollPane2.setViewportView(jTable2);

		jTextField2.setEnabled(false);

		jLabel2.setText("\u8ba2\u5355\u72b6\u6001");

		jLabel3.setText("\u603b\u6570\u91cf");

		jTextField3.setEnabled(false);

		jLabel4.setText("\u603b\u91d1\u989d");

		jTextField4.setEnabled(false);

		jButton2.setText("\u53d6\u6d88\u8ba2\u5355");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setText("\u70b9\u9910\u4eba");

		jTextField5.setEnabled(false);

		jMenu1.setText("\u67e5\u770b\u8ba2\u5355");
		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGap(27, 27,
																		27)
																.addComponent(
																		jScrollPane1,
																		0,
																		0,
																		Short.MAX_VALUE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGap(94, 94,
																		94)
																.addComponent(
																		jLabel1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		130,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton1)))
								.addGap(91, 91, 91)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton2)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jTextField2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										81,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										60,
																										Short.MAX_VALUE)
																								.addComponent(
																										jLabel3)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jTextField3,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										85,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(48,
																										48,
																										48)
																								.addComponent(
																										jLabel4)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jTextField4,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										78,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel5)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														jTextField5,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														73,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addComponent(
																										jScrollPane2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										536,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(37, 37,
																		37)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(24, 24, 24)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1)
												.addComponent(jLabel5)
												.addComponent(
														jTextField5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(31, 31, 31)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														254,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														217,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(6, 6, 6)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(jLabel4)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29).addComponent(jButton2)
								.addContainerGap(65, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents


	/*
	 * 通过orderid的模糊查询
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		vData1.clear();
		String id = this.jTextField1.getText();
		if ("".equals(id)) {
			table1AllShow();
			return;
		}
		List<Order> list = oService.queryByIdUser(id);
		if (list.size() != 0) {
			vData1.clear();
			for(Order order: list){
				Vector vOrder = new Vector();
				vOrder.add(order.getOrder_id());
				vOrder.add(order.getQuantity());
				vOrder.add(order.getTotal_price());
				vOrder.add(order.getOrder_status());
				vData1.add(vOrder);
				this.dtm = new DefaultTableModel(vData1, vHead1);
				this.jTable1.setModel(dtm);
			}
			return;
		}
		this.dtm = new DefaultTableModel(null, vHead1);
		this.jTable1.setModel(dtm);
	}
	/*
	 * 在未处理状态时取消订单
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		int row = this.jTable1.getSelectedRow();
		if (row == -1) {
			jPane.showMessageDialog(this, "请选择菜品！");
			return;
		}
		dtm = (DefaultTableModel) jTable1.getModel();
		String status = (String) dtm.getValueAt(row, 3);
		if(!"未处理".equals(status)){
			jPane.showMessageDialog(this, "订单已经处理，取消失败！");
			return;
		}
		String orderId = (String) dtm.getValueAt(row, 0);
		boolean hadDelete = oService.cancelStatus(orderId,"已取消");
		if (hadDelete) {
			jPane.showMessageDialog(this, "取消成功！");
			table1AllShow();
		}
	}
	/*
	 * 点击时显示detail
	 */
	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		int row = this.jTable1.getSelectedRow();
		dtm = (DefaultTableModel) jTable1.getModel();
		String orderId =  (String) dtm.getValueAt(row, 0);
		List<OrdersDetail> list = dService.queryDetail(orderId);
		vData2.clear();
		for (OrdersDetail i : list) {
			Vector vDatail = new Vector();
			vDatail.add(i.getMenu_id());
			vDatail.add(i.getName());
			vDatail.add(i.getAmount());
			vDatail.add(i.getUnit_price());
			vDatail.add(i.getTotal_price());
			vData2.add(vDatail);
		}
		DefaultTableModel model2 = new DefaultTableModel(vData2, vHead2);
		jTable2.setModel(model2);
		this.jTextField2.setText((String)dtm.getValueAt(row, 3));
		this.jTextField3.setText(String.valueOf(dtm.getValueAt(row, 1)));
		this.jTextField4.setText(String.valueOf(dtm.getValueAt(row, 2)));
	}


	/*
	 * 显示table1中所有的order信息
	 */
	private void table1AllShow() {
		List<Order> order = oService.queryByUser();
		this.vHead1 = new Vector();
		this.vData1 = new Vector();
		vHead1.add("订单编号");
		vHead1.add("订单商品数量");
		vHead1.add("订单总金额");
		vHead1.add("订单状态");
		for (Order i : order) {
			Vector vOrder = new Vector();
			vOrder.add(i.getOrder_id());
			vOrder.add(i.getQuantity());
			vOrder.add(i.getTotal_price());
			vOrder.add(i.getOrder_status());
			vData1.add(vOrder);
		}
		this.dtm = new DefaultTableModel(vData1, vHead1);
		this.jTable1.setModel(dtm);
	}

	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		boolean hadLogined = userService.iUser() != null ? true: false;
//		if(hadLogined){
//			jPane.showMessageDialog(this, "请先登录！");
//			System.exit(0);
//		}
		Users Iuser =  userService.iUser();
		this.jTextField5.setText(Iuser.getName());
		table1AllShow();
		this.vHead2 = new Vector();
		this.vData2 = new Vector();
		vHead2.add("套餐编号");
		vHead2.add("套餐名称");
		vHead2.add("套餐数量");
		vHead2.add("套餐单价");
		vHead2.add("套餐金额");
		this.dtm = new DefaultTableModel(vData2, vHead2);
		this.jTable2.setModel(dtm);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new OrderDetail().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	UserService userService = new UserService();
	JOptionPane jPane = new JOptionPane();
	Vector vHead2 = null;
	Vector vData2 = null;
	DefaultTableModel dtm = null;
	Vector vHead1 = null;
	Vector vData1 = null;
	OrderService oService = new OrderService();
	OrderDetailService dService = new OrderDetailService();
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}