/*
 * UserInfoEdit.java
 *
 * Created on __DATE__, __TIME__
 */

package com.edu.seiryo.ui;

import javax.swing.JOptionPane;

import com.seiryo.edu.entity.Users;
import com.seiryo.edu.service.UserService;

/**
 *
 * @author  __USER__
 */
public class UserInfoEdit extends javax.swing.JFrame {

	/** Creates new form UserInfoEdit */
	public UserInfoEdit() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setText("\u65e7\u5bc6\u7801");

		jLabel3.setText("\u65b0\u5bc6\u7801");

		jLabel4.setText("\u786e\u8ba4\u5bc6\u7801");

		jTextField1.setEnabled(false);

		jButton1.setText("\u786e\u8ba4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jMenu1.setText("\u8d26\u6237\u4fe1\u606f\u4fee\u6539");
		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(99, 99, 99)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										119, Short.MAX_VALUE)
								.addComponent(jButton2).addGap(138, 138, 138))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(78, 78, 78)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel1))
								.addGap(51, 51, 51)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(jTextField2)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														199, Short.MAX_VALUE)
												.addComponent(jTextField3)
												.addComponent(jTextField4))
								.addContainerGap(94, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(86, 86, 86)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										59, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addGap(44, 44, 44)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents
	/*
	 * 显示userName
	 */
	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		Users user = userService.iUser();
		this.jTextField1.setText(user.getName());
	}
	/*
	 * 重置
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextField2.setText("");
		this.jTextField3.setText("");
		this.jTextField4.setText("");
	}
	/*
	 * 信息修改确认
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String userName = this.jTextField1.getText();
		String oldPwd = this.jTextField2.getText();
		String newPwd1 = this.jTextField3.getText();
		String newPwd2 = this.jTextField4.getText();
		if("".equals(newPwd1) || "".equals(newPwd2) || "".equals(userName) || "".equals(oldPwd)){
			JOptionPane.showMessageDialog(this, "不能为空");
			return;
		}
		Users user = new Users();
		user.setName(userName);
		user.setPassword(oldPwd);
		int hadUser = userService.queryUser(user);
		if(hadUser == -1){
			JOptionPane.showMessageDialog(this, "旧密码错误");
			return;
		}
		if(!newPwd1.equals(newPwd2)){
			JOptionPane.showMessageDialog(this, "两次输入的新密码不一致");
			return;
		}
		boolean editSucess  = userService.editUserInfo(userName, newPwd1);
		if(editSucess){
			JOptionPane.showMessageDialog(this, "修改成功!");
			System.exit(0);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserInfoEdit().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	UserService userService = new UserService();
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}